sudo: required
language: python
services:
- docker

script:
- docker image build -t sakman/cps847 .

after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push sakman/cps847

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "CPS847-2"
  env: "Cps8472-env"
  bucket_name: "elasticbeanstalk-us-east-2-232327422743"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY